# -- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS O INNER JOIN ANIMAL_INS I ON(O.ANIMAL_ID = I.ANIMAL_ID)
WHERE (SEX_UPON_INTAKE NOT LIKE '%Spayed%' AND  SEX_UPON_INTAKE NOT LIKE '%Neutered%')
AND (SEX_UPON_OUTCOME LIKE '%Spayed%' OR SEX_UPON_OUTCOME LIKE '%Neutered%')