SELECT  FO.PRODUCT_ID
        ,FP.PRODUCT_NAME
        ,(SUM(FO.AMOUNT)*FP.PRICE) AS TOTAL_SALES
  FROM  FOOD_ORDER AS FO
  JOIN  FOOD_PRODUCT AS FP
    ON  FO.PRODUCT_ID = FP.PRODUCT_ID
 WHERE  DATE_FORMAT(PRODUCE_DATE,'%Y-%m') = '2022-05'
 GROUP
    BY  FO.PRODUCT_ID
 ORDER
    BY  TOTAL_SALES DESC, PRODUCT_ID

;